version: '3.8'

services:
  node-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      NODE_ENV: development
    restart: always