version: '3.8'

services:
  bytebank-shell:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps:/app/apps
      - ./packages:/app/packages
    environment:
      - NODE_ENV=production
