version: '3.8'

services:
  bytebank-shell:
    build:
      context: .
      dockerfile: apps/bytebank-shell/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/bytebank-shell/src:/app/src
      - ./packages/ui/src:/app/packages/ui/src
      - ./packages/utils/src:/app/packages/utils/src
      - ./packages/data-access/src:/app/packages/data-access/src
      - ./packages/eslint-config/src:/app/packages/eslint-config/src
      - ./packages/typescript-config/src:/app/packages/typescript-config/src
    environment:
      - NODE_ENV=development
    depends_on:
      - mfe-investments
    command: yarn run dev
  mfe-investments:
    build:
      context: .
      dockerfile: apps/mfe-investments/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./apps/mfe-investments/src:/app/src
      - ./packages/ui/src:/app/packages/ui/src
      - ./packages/utils/src:/app/packages/utils/src
      - ./packages/data-access/src:/app/packages/data-access/src
      - ./packages/eslint-config/src:/app/packages/eslint-config/src
      - ./packages/typescript-config/src:/app/packages/typescript-config/src
    environment:
      - NODE_ENV=development
    command: yarn run dev
  mfe-transactions:
    build:
      context: .
      dockerfile: apps/mfe-transactions/Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./apps/mfe-transactions/src:/app/src
      - ./packages/ui/src:/app/packages/ui/src
    environment:
      - NODE_ENV=development
    command: yarn run dev
