import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Importa SystemJS para carregar micro frontends */}
        <Script
          src="https://cdn.jsdelivr.net/npm/systemjs@6.14.2/dist/system.min.js"
          strategy="beforeInteractive"
        />
        {/* Importa o config do single-spa */}
        <Script src="/single-spa-config.js" strategy="afterInteractive" />
        {/* Importa o importmap para SystemJS */}
        <Script
          type="systemjs-importmap"
          src="/importmap.json"
          strategy="beforeInteractive"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
